# 1. Introduction to NumPy and Setup

**What is NumPy?**

**Definition:** NumPy is a powerful Python library used for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

**Importance in Data Science:** NumPy is fundamental to data science as it allows you to handle large datasets efficiently(NumPy arrays are much faster than Python lists because they are implemented in C.). It forms the basis for other scientific computing libraries like Pandas, SciPy, and scikit-learn.

**Installation**

To start using NumPy, you'll first need to install it. You can do this with pip (Python’s package installer) or using Anaconda.

Run these code in teminal:

**Using pip:**

pip install numpy

**using Anaconda (recommended if you're using the Anaconda distribution):**


conda install numpy

**Importing NumPy**

Once installed, you need to import NumPy into your script to use its functions:

In [ ]:
import numpy as np

This is a standard alias np that you'll use throughout your code to reference the NumPy library.

# Why do you think NumPy was made, when we already have Python lists?

 **the difference between lists and arrays.**

**If you wanted to multiply every number by 2**

first we multiply a **list** by 2 and

 then multiply  a **array** by 2

And  let see the differnce

**List:**
A list store multiple items in a single variable.

Think of it like a basket where you can keep different things (numbers, words, even other lists).


In [ ]:
numbers = [1, 2, 3, 4, 5]
print(numbers*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


 It repeats the list — it doesn't multiply each element by 2.

For this purpose we also use list comprehension But it is not efficient also dificult and slow

In [ ]:
mul_by_2 =[num*2 for num in numbers ]
print(mul_by_2)

[2, 4, 6, 8, 10]


**Array:**

A NumPy array (ndarray) is a powerful, efficient data structure that stores elements of the same type in a contiguous block of memory. It's more efficient than Python's native list.

NumPy arrays support multi-dimensional arrays, whereas Python lists are one-dimensional.

To create a NumPy array, we use np.array(), and we can pass a list or tuple as an argument.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr * 2)


[ 2  4  6  8 10]


unlike lists, NumPy arrays allow( every number multiplied by 2 ) element-wise operations:

**Reason 1: Element-wise operations**

lists don’t allow operations like * 2 on each item easily. we have to use a loop or list comprehension.
But with NumPy arrays, it’s built-in and fast.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Original:", arr)
print("Times 2:", arr * 2)# multiplies each element by 2
print("Plus 5:", arr + 5)# adds 5 to each element
print("Squared:", arr ** 2)# squares each element


Original: [1 2 3 4 5]
Times 2: [ 2  4  6  8 10]
Plus 5: [ 6  7  8  9 10]
Squared: [ 1  4  9 16 25]


All done element-wise — no loop needed!

**Reason 2: Speed**

If we had 1 million numbers and you wanted to multiply them all by 10 —
Which one do you think would be faster: Python lists with a loop,list comprehension or NumPy arrays?

Python loops are interpreted, which means slower.
NumPy is written in C (a compiled language) under the hood — so it processes huge arrays very fast, without you writing loops or list comprehension

In [ ]:
arr * 10


array([10, 20, 30, 40, 50])

on a million elements is much faster than a Python loop or list comprehension

**🧠 Quick Recap (What we’ve Learned So Far)**

| Concept                 | NumPy Power 💥                      |
| ----------------------- | ----------------------------------- |
| List vs Array           | Arrays allow direct math operations |
| Speed                   | NumPy is much faster for big data   |
| Element-wise Operations | Built-in (no loop needed)           |


# Array Creation (More Powerful Ways)

**Using Built-in Functions:**

np.zeros(): Creates an array of zeros.

In [ ]:
np.zeros(6) # create  1D array of zero which has 6 elements (np.zero(number of elements))
zero=np.zeros((2,3)) # create 2D array of zero which has 2 raws and 3 columns

np.fill_diagnal(matrix,diagnal_values): update diagnal values of a matrix

In [ ]:
np.fill_diagonal(zero,1) # update diagnal values of zero matrix with 1
np.fill_diagonal(zero,(1,2)) # and 2
print(zero)

[[1. 0. 0.]
 [0. 2. 0.]]


np.ones(): Creates an array of ones.

In [ ]:
np.ones(6)# create  1D array of ones which has 6 elements "np.ones(number of elements)"
np.ones((2,3)) # create 2D array of zero which has 2 raws and 3 columns "np.ones((raws,columns))"

array([[1., 1., 1.],
       [1., 1., 1.]])

np.empty(): Creates an array without initializing values (it can be random or garbage values).

In [ ]:
np.empty(7)# create  1D array of  random or garbage values  which has 7 elements "np.empty (number of elements)"
np.empty((3,3)) # create 2D array of  random or garbage values  which has 3 raws and 3 columns "np.empty((raws,columns))"

array([[ 15.2,  65. , 101.2],
       [ 16.1,  68. , 101.1],
       [ 14.9,  62. , 101.5]])

np.eye(): create identity array

In [ ]:
np.eye(4) # crate 4x4 identity array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**converting list into array**

In [ ]:
Number = [1, 2, 3, 4]
arr = np.array(Number)
print(arr)


[1 2 3 4]


**Generate arrays without List**

using np.arange(start,stop)

In [ ]:
arr=np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


It includes the start (0) but excludes the stop (10) — just like Python’s range().

**Note**  : if we give only one number  to np.arange  it will considered stop ( e.g  np.arrange(stop)) and  array start from zero

In [ ]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]




> You can also set a step size: using np.arange(start,stop,step-size)



In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

Starts at 0

Goes up by 2 each time

Stops before 10

**Evenly spaced numbers with linspace(start,stop,equally divide)**

think of it like a wire divided into equall parts

In [ ]:
np.linspace(0,1,5) # divide wire ( 0 to 1) into 4 equall parts (5 not included)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

It includes both 0 and 1 (unlike arange, which excludes the stop).

It makes 5 equally spaced numbers between them:

0 → 0.25 → 0.5 → 0.75 → 1


np.array() → converting a list into array

np.arange() → create an array with a step

np.linspace() → fixed number of evenly spaced values


**Note:** These functions always create 1D array

# : Array properties

**Shape:**

Shape tells us how many rows and columns an array has.
Example:

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"shape:{arr.shape}") # (raws,columns)



shape:(2, 3)


shape:(raws,columns)

2 = number of rows

3 = number of columns

**Size:** The total number of elements in the array.

In [ ]:
print(arr.size)  # Output: 6


6


**Number of Dimensions (ndim)**: The number of dimensions (axes) the array has.

In [ ]:
print(arr.ndim)  # Output: 2 (since it's a 2D array)


2


**Item Size:** The size of each element in bytes.

In [ ]:
print(arr.itemsize)  # Output: 8 (on 64-bit systems)


8


Data Type (dtype): The type of data stored in the array (e.g., int, float,str)

In [ ]:
print(arr.dtype)

int64


# Data Type Cantrol

**Data Type (dtype):** The type of data stored in the array (e.g., int, float,str).

In [ ]:
print(arr.dtype)  # Output: int64 (on 64-bit systems)
arr_float = np.array([1.0, 2.0, 3.0, 4.0])
print(arr_float.dtype)  # Output: float64 (on 64-bit systems)
a = np.array([True, False, True])
print(a.dtype)  # Output: bool
A=np.array(["hello","python"])
print(A.dtype) # Output: <U6 which is string with 6 characters

int64
float64
bool
<U6


**Type coercion or upcasting.**

NumPy must make every item in an array the same dtype. To do this, it finds the "most general" or "highest-level" data type that can represent all the elements without losing information

**Example:**

if an array contain all data type(int,float,str).it make the whole array

 dtype('<U32') which is string

 if an array contain data type(int,float) it make the whole array

 dtype('float64')

In [ ]:
arr34=np.array([1,2,3.5,6,4.8,"Hello","python"])
print(arr34.dtype)#output: <U32 It sees one str, so to be safe, it makes the whole array <U32
arr12=np.array([1, 2.0, 3,4])
print(arr12.dtype) # output: float64 It sees one decimal, so to be safe, it makes the whole array float64.

<U32
float64


**How would you create a NumPy array of [10, 20, 30] but force NumPy to store them as float?**

In [ ]:
arr=np.array([10,20,30],dtype=np.float64)
print(arr)

[10. 20. 30.]


**This is where dtype gets really important. Notice those 64s in int64 and float64? That's the number of bits (the amount of memory) each number uses.**

**dtype:** int8 ->Range of Numbers It Can Store->  -128 to 127 ->Real-World Application -> Very small numbers.

**dtype:** uint8 ->Range of Numbers It Can Store -> 0 to 255 ->Real-World Application ->**Image data!** Each pixel's color (Red, Green, Blue) is a value from 0-255. Using uint8 instead of int64 can make an image file 8x smaller!

**dtype:** int32 -> Range of Numbers It Can Store-> -2.1 billion to 2.1 billion  ->Real-World Application -> Most day-to-day integers.

**dtype:** int64 ->Range of Numbers It Can Store->...-9 quintillion to 9 quintillion... -> Real-World Application -> Massive numbers. Default for safety.

**dtype:** float32 ->Range of Numbers It Can Store-> "Single precision" decimal ->Real-World Application ->Less precise, but uses half the memory of float64. Very common in Machine Learning where "good enough" precision is fine and speed is vital.


**dtype:** float64 ->Range of Numbers It Can Store->  "Double precision" decimal->Real-World Application -> Super high precision. Default for safety. Critical for scientific calculations where tiny rounding errors add up.

**Data Science,** you often work with millions of rows. Choosing float32 over float64 could cut your memory usage in half!


you are storing a dataset of human ages. You know that age can't be negative and will never be over, say, 130. What would be the most memory-efficient dtype to use?

**Answer:**
dtype=uint8 (because it stores whole numbers from 0 to 255, which perfectly fits the data and uses the least memory)

In [ ]:
age=np.array([20,40,70,100,90,45,84],dtype=np.uint8)
print(age)

[ 20  40  70 100  90  45  84]


**casting.**

 changing data type

>**.astype():**
It always creates a new copy of the array with the new type.

**The most important:** When you cast from a float to an int, NumPy truncates (chops off the decimal). It does not round.

In [ ]:
# Array of floats
float_arr = np.array([1.2, 3.8, 5.5, -2.9])
print(f"Original array: {float_arr}")

# Cast to integer
int_arr = float_arr.astype(np.int32)
print(f"Casted array:   {int_arr}")

Original array: [ 1.2  3.8  5.5 -2.9]
Casted array:   [ 1  3  5 -2]


**Notice** 3.8 became 3, not 4.

You can also use this to clean data. If you have an array of numbers stored as text (e.g., ['10', '20']), you can't do math on them until you cast them.

In [ ]:
arr=np.array(['10','20','30'])
arr=arr.astype(np.int32)
print(arr.dtype)

int32


You have an array: arr = np.array([0, 1, 50, 0, -20]). What will arr.astype('bool') look like?

In [ ]:
arr = np.array([0, 1, 50, 0, -20])
arr=arr.astype(np.bool)
print(arr) # in bool 0 for False and other numbers for True

[False  True  True False  True]


**Structured Arrays: (columns_Name with data type)**

So far, we've said all items in an array must be the same type. That's mostly true.

But what if you have array like a row from a spreadsheet? ('Alice', 25, 50000.0) That's a string, an integer, and a float.



**A Structured Array** lets you create a custom dtype

Instead of a same dtype array(), you are creating columns with custom data type (columns: one for a name with str, one for an age with int, one for a salary with float.)

**You define this custom dtype as a list of tuples: ("column_name", "dtype_code")**

its like creating the fundamental structure for a spreadsheet. (columns with their data type)

In [ ]:
# 1. Define the custom 'dtype'
custom_dtype=[("name","U10"),("age","i4"),("sallary","f8")]
# 'U10' = 10-char string
# 'i4' = 32-bit integer (4 bytes)
# 'f8' = 64-bit float (8 bytes)
# 2. Create an array with this dtype
data = np.array([('Alice', 25, 50000.0),
                 ('Bob', 30, 60000.0),
                 ('Carol', 22, 45000.0)],dtype=custom_dtype)
print(data)
# remimber data is not a 2D array its a 1D array of tuples

[('Alice', 25, 50000.) ('Bob', 30, 60000.) ('Carol', 22, 45000.)]


This is still one single, continuous block of memory (which is why it's fast!). But here's the magic: you can now access columns by name.

In [ ]:
# Get all names
print(data["name"])
# Output: ['Alice' 'Bob' 'Carol']
print(data["age"])
# Output: [25 30 22]
print(data["sallary"])
# Output: [50000.  60000. 45000.]
# You can even do math on a column
print(f"Total_sallary:{data["sallary"].sum()}")

['Alice' 'Bob' 'Carol']
[25 30 22]
[50000. 60000. 45000.]
Total_sallary:155000.0


Real-World Application: This is how NumPy reads complex data from scientific files or CSVs before you load them into a Pandas DataFrame. In fact, a Pandas DataFrame is basically a more user-friendly version of this concept.

# Reshaping arrays

**2️⃣ Creating and Reshaping Arrays (into 2D)**

Sometimes we create a 1D array and want to reshape it into 2D or even 3D.

In [ ]:
arr = np.arange(0,20,2) # shape:(10,), 1D array
reshaped_arr=arr.reshape(5,2) # reshape into (5,2) 5 raws and 2 columns
print(reshaped_arr)

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


**⚠️ Important Rule:**

The total number of elements must stay the same when reshaping.
Example:

(10,) → (5, 2) ✅ (10 elements in both)

(10,) → (3, 3) ❌ (needs 9 elements)

**3️⃣ Using -1 for Auto Calculatio**n

You can use -1 to let NumPy figure out one dimension automatically:

In [ ]:
arr.reshape(2,-1) # 2 raws and  NumPy figure out columns automatically
arr.reshape(-1,2) # 2 columns and NumPy figure out raws automatically

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

**Recap so far in Level 2:**

.shape → tells rows & columns

.reshape(r, c) → changes shape (same number of elements)

-1 → lets NumPy auto-calculate one dimension

| Dimension | Shape Example                          | What it means                          |
| --------- | -------------------------------------- | -------------------------------------- |
| **1D**    | `(5,)`                                 | Just a single list of numbers → 1 axis |
| **2D**    | `(rows, cols)` e.g. `(3, 4)`           | Table with rows & columns → 2 axes     |
| **3D**    | `(pages, rows, cols)` e.g. `(2, 3, 4)` | Multiple 2D tables stacked → 3 axes    |


**1: .flatten()**

👉 Returns a flattened (1D) copy of the multi-dimension array.

👉 It always creates a new 1D array, so changes don’t affect the original.

In [ ]:

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
flattened_arr = arr.flatten()
print(flattened_arr)  # Output: [1, 2, 3, 4, 5, 6]

[1 2 3 4 5 6]


Changing flattened_arr did not affect original array.

In [ ]:
flattened_arr[0] = 999
print(arr)# original stay same  # output: [[1  2   3]
                                #          [4   5   6]]


[[1 2 3]
 [4 5 6]]


**2: .ravel()**

👉 Returns a flattened (1D) view of multi-dimension array.

👉 If possible, it does not make a copy → it just gives another “view” of the same data (so changes may affect the original array).

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
r=arr.ravel()
print(r) # output:[1 2 3 4 5 6]


[1 2 3 4 5 6]


**Note:** changing in revaled array (r) also changed original array (arr)

(because it’s a view).

In [ ]:
r[0] = 100
print(arr)       # [[100   2   3]
                 #  [  4   5   6]]

[[100   2   3]
 [  4   5   6]]


.ravel() → returns a view (fast, but linked to original)

.flatten() → returns a copy (safe, but uses more memory)

👉 Use .ravel() when you just need a quick 1D view.

👉 Use .flatten() when you don’t want to risk modifying the original.

#  Indexing & Slicing in NumPy
Indexing & slicing lets you pick specific data from arrays — just like picking certain rows & columns in a table.

**1️⃣ Indexing in 1D Arrays**

in python index start from zero

In [ ]:
arr=np.arange(1,10)
print(arr)
print(arr[0]) # select or pick first element
print(arr[-1]) # select or pick last element
print(arr[2]) # select or pick 3rd element

[1 2 3 4 5 6 7 8 9]
1
9
3


**Advanced or "Fancy" Indexing in 1D array**

picking multiple items from anywhere in the array, in any order you want.


You have an array of test scores. How would you use fancy indexing to select the first, third, and last scores?

In [ ]:
scores = np.array([88, 92, 100, 75, 83, 95])
# Your code here:
selected_scores = scores[[0,2,-1]]
print(selected_scores)

[ 88 100  95]


**Slicing in 1D Arrays**

Slicing lets you take a range of elements

In [ ]:
print(arr[0:5]) # select or pick elements from index 0 to 5
print(arr[:7]) # select or pick 1st seven elements
print(arr[2:]) # select or pick elements from index 2 to last
print(arr[2:7]) # select or pick elements from index 2 to 7
print(arr[::2]) # selects every second element starting from the beginning of the array.

[1 2 3 4 5]
[1 2 3 4 5 6 7]
[3 4 5 6 7 8 9]
[3 4 5 6 7]
[1 3 5 7 9]


 **remember**:  in python index start from zero (not one)

**2️⃣ Indexing in 2D Arrays**

In [ ]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(arr2d[0,0]) # pick element at first raw , first column
print(arr2d[2,1]) # pick element at 3rd raw , 2nd column

1
8


 **Note:**
 it always 1st select raw and then select column of selected raw

**selecting multiple elements from anywhere in the array**

In [ ]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# we want select multiple  elements at [0, 1],[1, 2], and [2, 0] in 2D array
print(arr2d[[0,1,2],[1,2,0]])

[2 6 7]


Given the arr2d from above, how would you select the center element (5) and the bottom-right element (9)?

5 at [1,1] and 9 at [2,2]

In [ ]:
print(arr2d[[1,2],[1,2]])

[5 9]


**Slicing in 2D Arrays**

Slicing lets you take a range of rows or columns.

In [ ]:
print(arr2d[0]) # pick first raw
print(arr2d[1]) # pick  2nd raw
print(arr2d[0:2]) # pick raw 1 and 2
# pick raws from index 0 to 1 ( index 2 not include )
print(arr2d[0:3]) # pick raw 1 to 3
# pick raws from index 0 to 2 (index 3 not included )



[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr2d[0:2,1:3]) # pick raws 1 to 2 and columns 2 to 3

[[2 3]
 [5 6]]


0:2 → rows from index 0 up to (but not including) 2

1:3 → columns from index 1 up to (but not including) 3

**remember:** it always 1st select raws and then select columns of selected raws

**pick multiple rows from anywhere in 2D array**

In [ ]:
arr2d = np.array([
    [1, 2, 3],  # Row 0
    [4, 5, 6],  # Row 1
    [7, 8, 9]   # Row 2
])
print(arr2d[[0,2]]) # select or pick row 1 and row 3

[[1 2 3]
 [7 8 9]]


**Selecting Entire Rows or Columns**

In [ ]:
print("all raws and all columns:",arr2d[:,:])
print(" 1st raw ,all columns:",arr2d[0,:])
print("all raws,3rd column:",arr2d[:,2])
print("raws 1 and 2 ,all columns:",arr2d[0:2,:])
print("all raws ,columns 1 to 3:",arr2d[:,0:3])


all raws and all columns: [[1 2 3]
 [4 5 6]
 [7 8 9]]
 1st raw ,all columns: [1 2 3]
all raws,3rd column: [3 6 9]
raws 1 and 2 ,all columns: [[1 2 3]
 [4 5 6]]
all raws ,columns 1 to 3: [[1 2 3]
 [4 5 6]
 [7 8 9]]


**Remimber:** when we select only raws ,python automatically select all columns of selected raws

Example:

In [ ]:
print(arr2d[0]) # pick first raw,all columns
print(arr2d[0:2]) # pick raw 1 and 2,all columns

[1 2 3]
[[1 2 3]
 [4 5 6]]


**Combining Fancy and Basic Indexing:**
You can mix "fancy" indexing with regular slicing. This is where it really shines.

In [ ]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# pick Row 0 and Row 2, but only their last two columns (columns 1 and 2).
print(arr2d[[0,2],1:3])
# pick Row 1, but only the first and last columns (columns 0 and 2).
print(arr2d[1,[0,2]])

[[2 3]
 [8 9]]
[4 6]


# Array Operations

**Mathematical Operations(on 1D arrays):**

NumPy allows us to perform element-wise operations on arrays. This means that operations like addition, subtraction, multiplication, and division are applied element by element.

**Addition:** Adding two arrays element by element.

In [ ]:
arr1 = np.array([1, 2,3])
arr2 = np.array([4, 5, 6])
result = arr1+arr2 # OR np.add(arr1,arr2)
print(result)


[5 7 9]


**Subtraction:** subtract two arrays element by element

In [ ]:
subtraction=arr2-arr1
print(subtraction)

[3 3 3]


**Multiplication:** multiply two arrays element by element

In [ ]:
multiplication = arr1 * arr2 # OR np.multiply(arr1,arr2)
print(multiplication)


[ 4 10 18]


**Division:** divide two arrays element by element




In [ ]:
divide=arr1/arr2
print(divide)

[0.25 0.4  0.5 ]


**Exponentiation**   Element-wise exponentiation

In [ ]:
exponentiation = arr1 ** 2  # Element-wise exponentiation
print(exponentiation)


[1 4 9]


**1️⃣ Aggregation Functions**

In NumPy, aggregation means combining multiple values into one result (sum, mean, min, max, etc.).

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(np.sum(arr))   # 21  → sum of all elements
print(np.mean(arr))  # 3.5 → mean of all elements
print(np.min(arr))   # 1   → smallest value
print(np.argmin(arr)) # 0 -> position of smallest value
print(np.max(arr))   # 6   → largest value
print(np.argmax(arr)) # 5-> position of largest value
print(np.std(arr)) # 1.707825127659933 -> standard daviation

21
3.5
1
0
6
5
1.707825127659933


**2️⃣ Axis Concept**

Axis tells NumPy which direction to perform the operation.



**np.sum(arr,axis=1):**

Meaning: For each row, add all its columns.

Result: 1D array where each element is the sum of one row.



In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(np.sum(arr,axis=1))  # [6, 15]


[ 6 15]


Row 1 → 1+2+3 = 6

Row 2 → 4+5+6 = 15

**np.mean(arr,axis=0):**

Meaning: For each column, take the average of its rows.

Result: 1D array where each element is the mean of one column

In [ ]:
print(np.mean(arr,axis=0))  # [2.5, 3.5, 4.5]


[2.5 3.5 4.5]


Column 1 → (1+4)/2 = 2.5

Column 2 → (2+5)/2 = 3.5

Column 3 → (3+6)/2 = 4.5

📌 Easy memory trick:

axis=0 → column-wise (operate downwards).

axis=1 → row-wise (operate sideways).

In [ ]:
print(np.sum(arr,axis=0))  # [5 7 9] → sum column-wise
print(np.sum(arr,axis=1))  # [6 15]  → sum row-wise


[5 7 9]
[ 6 15]


**Square Root:**

In [ ]:
square_root=np.sqrt(arr2)
print(square_root)

[2.         2.23606798 2.44948974]


**Universal Functions (ufuncs):**

ufuncs are functions that operate element-wise on arrays. Some of the most useful ufuncs include:

np.sin(), np.cos(): Trigonometric functions

np.exp(): Exponentiation

np.log(): Logarithms

np.abs(): Absolute value

In [ ]:
arr = np.array([0, 30, 60, 90])
print(np.sin(np.radians(arr))) # Sine values of angles
print(np.cos(np.radians(arr))) # Cosine values of angles
print(np.exp(arr)) # Exponentiation
print(np.log(arr)) # Logarithms
print(np.abs(arr)) # Absolute values

[0.        0.5       0.8660254 1.       ]
[1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17]
[1.00000000e+00 1.06864746e+13 1.14200739e+26 1.22040329e+39]
[      -inf 3.40119738 4.09434456 4.49980967]
[ 0 30 60 90]


/tmp/ipython-input-1794221836.py:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr)) # Logarithms


**Array Comparisons:**

You can compare two arrays element by element. The result is a boolean array.





In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 4])
result=arr1==arr2
print(result)

[ True  True False]


**Greater Than:**

In [ ]:
result=arr1>arr2
print(result)

[False False False]


**Greater Than or equall to :**

In [ ]:
result=arr1>=arr2
print(result)

[ True  True False]


**Less Than:**

In [ ]:
result=arr1<arr2
print(result)

[False False  True]


**Less Than or Equal to:**

In [ ]:
result=arr1<=arr2
print(result)

[ True  True  True]


**Not Equal:**

In [ ]:
result=arr1!=arr2
print(result)

[False False  True]


**Logical Operations:**

You can also perform logical operations such as np.logical_and(), np.logical_or().

In [ ]:
arr1 = np.array([True, False, True])
arr2 = np.array([False, False, True])
result=np.logical_and(arr1,arr2)
print(result)  # Output: [False False  True]
# np.logical_or()
result=np.logical_or(arr1,arr2)
print(result)  # Output: [ True False  True]


[False False  True]
[ True False  True]


# Boolean Indexing & Conditional Selection
This is where NumPy feels smart — you can ask it for only the values you want.

**1️⃣ Boolean Conditions**

In [ ]:
arr=np.arange(1,10)
print(arr)
print(arr<5)

[1 2 3 4 5 6 7 8 9]
[ True  True  True  True False False False False False]


This doesn’t give the numbers yet — it gives True/False for each element:

Your array of [True, False] answers is called a boolean mask

**2️⃣ Using Conditions to Select Values**

In [ ]:
arr[arr<5]

array([1, 2, 3, 4])

**If:**

In [ ]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])


What will arr2d[arr2d % 2 == 0] return?

In [ ]:
arr2d[arr2d%2==0] # all even numbers

array([2, 4, 6, 8])

In [ ]:
np.where(arr2d%2==0)

(array([0, 1, 1, 2]), array([1, 0, 2, 1]))

**Note:** it flattens the result into a 1D array of matching values.

All even numbers from the 2D array, in a single row.

**Update using condition**

 If we want to keep the 2D shape but replace non-even numbers with something (e.g., 0), we can do: bold text

In [ ]:
arr2d[arr2d%2!=0]=0 # select non-even number and then replace with zero
print(arr2d)

[[0 2 0]
 [4 0 6]
 [0 8 0]]


# Using multiple conditions to select values

📌 Rules to Remember:

Use & for AND, | for OR

Each condition must be in parentheses — otherwise, Python gets confused.

**Multiple Conditions with & (AND)**

In [ ]:
import numpy as np

arr = np.arange(1, 11)  # [1 2 3 4 5 6 7 8 9 10]
arr=arr.reshape(2,-1)
# Condition: greater than 3 AND even
result=arr[(arr>3)&(arr%2==0)]
print(result)

[ 4  6  8 10]


**note:** python apply both conditions saperatily and then take common values "like intersection (condition1)intersection(condition2)"

In [ ]:
arr[(arr < 5) & (arr > 8)] # if no common value result will be empty array

array([], dtype=int64)

**Multiple Conditions with| (OR)**

In [ ]:
arr[(arr < 5) | (arr > 8)]


array([ 1,  2,  3,  4,  9, 10])

**Note:** python apply both condition saperatily

and then  combines them "like take union {(condition1)union(condition2)}" **Rule for  no common value exist in both**

condition1:All numbers less than 5 → [1, 2, 3, 4]

condition2:All numbers greater than 8 → [9, 10]

no common value in both condition so it combine them

**if  common value exist in both conditions it will give entire array:**

In [ ]:
arr[(arr > 5) | (arr < 8)]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

condition1:(arr > 5) →Picks [6, 7, 8, 9, 10]

condition2:(arr < 8) →Picks [1, 2, 3, 4, 5, 6, 7]

Notice that 6 and 7 appear in both conditions, so together they cover 1 through 10 with no gaps.

✅ Result = entire array.

💡 Rule of Thumb: If max of 1st condition ≥ min of 2nd condition ,it mean common value exist in both condition then ✅ Result = entire array.

**Using condition to replace values**

**Case 1**

> np.where(condition ,value_if_true,value_if_false)

We have a list of student grades. We want to label anyone with a grade over 70 as "Pass" and everyone else as "Fail."


In [ ]:
import numpy as np

# 1. Our array of grades
grades = np.array([55, 92, 75, 68, 81, 100])
# np.where(condition, "Pass", "Fail")
results = np.where(grades>=70,"pass","fail")
print(results)

['fail' 'pass' 'pass' 'fail' 'pass' 'pass']


It checked every single value instantly and gave us a new array of results. This is element-wise logic.

**Practice Question**

You have an array of temperatures. temps = np.array([-5, 12, 0, 22, -10, 1])

How would you use np.where() to create a new array that labels everything above 0 as "Above Freezing" and everything else as "Freezing"?

In [ ]:
temps = np.array([-5, 12, 0, 22, -10, 1])
result=np.where(temps>0,"Above Freezing","Freezing")
print(result)

['Freezing' 'Above Freezing' 'Freezing' 'Above Freezing' 'Freezing'
 'Above Freezing']


**case 2**

Let we have array of  sales = np.array([150, 200, -10, 120, -5, 300])

 we want to change negitive numbers with 0 and
keep the  all other  numbers original

> np.where(condition,value_if_True,array)





In [ ]:
# Our array of product sales with errors
sales = np.array([150, 200, -10, 120, -5, 300])

# Condition: sales < 0
# Value if True: 0
# Value if False: sales (the original value)
cleaned_sales = np.where(sales<0,0,sales)

print(cleaned_sales)

[150 200   0 120   0 300]


**Practice Question:** You have an array of website visitor counts. Your sensor maxes out at 1000. Any reading of 1000 is "capped" and should be labeled as "1000+" to show it might be higher. All other numbers should stay as they are. visitors = np.array([520, 1000, 810, 1000, 650])

How would you create an array that looks like ['520', '1000+', '810', '1000+', '650']? (Hint: The output array will need to be strings, not numbers.)

In [ ]:
visitors = np.array([520, 1000, 810, 1000, 650,700]).reshape(2,3) # 2x3 array
# We must use .astype(str) to allow the array to hold both numbers (as strings) and the '1000+' string.
result=np.where(visitors==1000,"1000+",visitors.astype(str))
print(result)

[['520' '1000+' '810']
 ['1000+' '650' '700']]


**Data scientists use this constantly for:**

**Replacing errors:** Changing all -999 values to 0 or np.nan (Not a Number).

**Capping values (Flooring/Ceiling):** "Any value over 100 is an error, just make it 100."

np.where(scores > 100, 100, scores)

**Creating new categories:** "Anyone with sales > 500 is 'Top Tier', everyone else is 'Standard'."

**What happens if you only give it the condition? np.where(condition)**

It gives us the indices (coordinates) of where the condition is True.

This is perfect for when you don't want to replace values, but just want to find them.

**🗺️ 1D Array Example:**

In [ ]:
grades = np.array([55, 92, 75, 68, 81, 100])
# Question: "WHERE are the grades > 90?"
np.where(grades>90) # output:(array([1, 5]),) means value at index 1 and 5 are greater then 90 (condition is true at index 1 and 5 )

(array([1, 5]),)

**🗺️ 2D Array (Grid) Example:**

In [ ]:
grid = np.array([
    [1, 5, 3],  # Row 0
    [8, 2, 9],  # Row 1
    [4, 6, 7]   # Row 2
])
# Question: "WHERE are the values > 5?"
np.where(grid>5)

(array([1, 1, 2, 2]), array([0, 2, 1, 2]))

**Output:** (array([1, 1, 2, 2]), array([0, 2, 1, 2]))

**You read them as pairs:**

(Row 1, Col 0) -> grid[1, 0] is 8

(Row 1, Col 2) -> grid[1, 2] is 9

(Row 2, Col 1) -> grid[2, 1] is 6

(Row 2, Col 2) -> grid[2, 2] is 7

**Practice Question:** You have a 2D array representing a game board. 0 is empty, 1 is Player 1, and 2 is Player 2. board = np.array([ [0, 1, 0], [2, 1, 0], [0, 2, 1] ])

How would you find the (row, col) coordinates of all of Player 1's pieces?

In [ ]:
board = np.array([
    [0, 1, 0],
    [2, 1, 0],
    [0, 2, 1]
])
result=np.where(board==1)
print(result)

(array([0, 1, 2]), array([1, 1, 2]))


# Array Manipulation

In this section, we'll learn how to manipulate arrays by concatenating, stacking, splitting, transposing, and adding/removing elements.


**1:
Concatenation: Joining two or more arrays along a specified axis (rows or columns).**

```
np.concatenate(): Joins arrays along an existing axis.
```





**For 1D arrays(axis=0)**

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.concatenate((arr1, arr2))  # Default is axis 0 (along the rows)
print(result)  # Output: [1 2 3 4 5 6]


[1 2 3 4 5 6]


**Note** 1D arrays only have one axis (axis= 0).

**For 2D array**
>  default axis=0 join vertically(add raws)



In [ ]:

arr1 = [
    [5, 10, 15, 20],
    [25, 30, 35, 40],
    [45, 50, 55, 60]
]
arr2 = [
    [1, 2, 3,3],
    [4, 5, 6,6],
    [7, 8, 9,9]
]


result=np.concatenate((arr1,arr2))# default axis=0 join vertically (add raws)
print(result)


[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]
 [ 1  2  3  3]
 [ 4  5  6  6]
 [ 7  8  9  9]]


**Rule:** for axis=0 Number of columns must be same otherwise it give error


>axis=1 join horizantally "side-by-side" (add columns)



In [ ]:
result2=np.concatenate((arr1,arr2),axis=1) # axis=1 join Horizantally (add columns)
print(result2)

[[ 5 10 15 20  1  2  3  3]
 [25 30 35 40  4  5  6  6]
 [45 50 55 60  7  8  9  9]]


**Rule:** for axis =1 numbers of raws must be same otherwise it give error


**2:
Stacking: Combining arrays along a new axis.**

**For 1D Arrays:**

remimber:we can not join 1D arrays vertically by concatenate() method

for this purpose we use:

np.vstack(): Stacks arrays vertically (row-wise).







In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3=np.array([7,8,9])
result=np.vstack((arr1,arr2,arr3))
print(result)
# Output:
# [[1 2 3]
#  [4 5 6]
#  [7,8,9]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Rule** Numbers of elements in all arrays must be same

**np.hstack(): Stacks arrays horizontally (column-wise).**

In [ ]:
result2=np.hstack((arr1,arr2,arr3))
print(result2)

[1 2 3 4 5 6 7 8 9]


**np.dstack(): Stacks arrays depth-wise (along a new third axis).**

dstack → pairs elements into [x,y,z] and stacks in depth

In [ ]:
result = np.dstack((arr1, arr2,arr3))
print(result)



[[[1 4 7]
  [2 5 8]
  [3 6 9]]]


**my observation** it convert rows into columns of all arrays then stack horizontally

**For 2D arrays:**

np.vstack(): Stacks arrays vertically (row-wise).

In [ ]:
arr1 = [
    [5, 10, 15, 20],
    [25, 30, 35, 40],
    [45, 50, 55, 60]
]
arr2 = [
    [1, 2, 3,3],
    [4, 5, 6,6],
    [7, 8, 9,9],
    ]

result=np.vstack((arr1,arr2))
print(result)

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]
 [ 1  2  3  3]
 [ 4  5  6  6]
 [ 7  8  9  9]]


**Rule:** Number of columns must be same otherwise it give error

**np.hstack(): Stacks arrays horizontally (column-wise).**

In [ ]:
result2=np.hstack((arr1,arr2))
print(result2)


[[ 5 10 15 20  1  2  3  3]
 [25 30 35 40  4  5  6  6]
 [45 50 55 60  7  8  9  9]]


**Rule:** number of raws must be same otherwise it give error

**np.dstack(): Stacks arrays depth-wise (along a new third axis).**

dstack → pairs elements into [x,y] and stacks in depth (3×4×2)

In [ ]:
result=np.dstack((arr1,arr2))
print(result)

[[[ 5  1]
  [10  2]
  [15  3]
  [20  3]]

 [[25  4]
  [30  5]
  [35  6]
  [40  6]]

 [[45  7]
  [50  8]
  [55  9]
  [60  9]]]


**3:
Splitting 1D  Arrays**

**np.split(array,number of sub-array):** Splits an array into multiple sub-arrays.

You can specify the number of splits or the indices where the splits should happen.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
result=np.split(arr,3) # Splits whole array into 3 sub-arrays
print(result)
# Output: [array([1, 2]), array([3, 4]), array([5, 6])]
result2=np.split(arr[3:6],3)  # Splits array from index 3 to 5 (6 not include)  into 3 sub-arrays
print(result2)
# output: [array([4]), array([5]), array([6])]

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([4]), array([5]), array([6])]


Note: number of elements of arr=6
number of sub-array=3
number of elements of each sub-array=6/3=2

**RULE:**  numbers of sub-arrays must divide numbers of elements of main- array

**Splitting 2D Arrays**

**axis=1:**

**np.split(array,number of sub-array,axis=1):**  Split array into sub- arrays along columns

In [ ]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
result = np.split(arr2D, 3,axis=1)  # Split into 3 arrays along columns
print(result)
# Output: [array([[1],
#                 [4]]),
#          array([[2],
#                 [5]]),
#          array([[3],
#                 [6]])]


[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [ ]:
arr2D = np.array([[1, 2, 3,4,5,6], [7,8,9,10,11,12]])
result2=np.split(arr2D,3,axis=1)
print(result2)

[array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]])]


**Easy Method**

**np.hsplit(array,number of sub-array):** Splits the array horizontally (along columns for 2D arrays).

In [ ]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
result = np.hsplit(arr2D, 3)  # Split into 3 arrays along columns
#print(result)
# Output: [array([[1],
#                 [4]]),
#          array([[2],
#                 [5]]),
#          array([[3],
#                 [6]])]


In [ ]:
arr2D = np.array([[1, 2, 3,4,5,6], [7,8,9,10,11,12]])
result2=np.hsplit(arr2D,3)
print(result2)
# split all raws,all columns of array into 3 sub_array along columns
result2=np.hsplit(arr2D[:,:],3)
print(result2)
# split 1st two columns(from index 0 to 1),all raws of array into 2 sub_array along columns
result3=np.hsplit(arr2D[:,0:2],2)
print(result3)

[array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]])]
[array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]])]
[array([[1],
       [7]]), array([[2],
       [8]])]


Note: number of columns of arr2D=6

number of sub-array=3

number of columns of each sub-array=6/3=2

**RULE:**  numbers of sub-arrays must divide numbers of columns (that are spliting) of main- array

**axis=0:**


**np.split(array,number of sub-array,axis=0):**  Split array into sub- arrays along raws

In [ ]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
result = np.split(arr2D, 2,axis=0)  # Split into 2 sub-arrays along raws
print(result)
# Output: [array([[1, 2, 3]]), array([[4, 5, 6]])]

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [ ]:
arr2D = np.array([[1, 2, 3,4,5,6], [7,8,9,10,11,12],[13,14,15,16,17,18]])
result2=np.split(arr2D,3,axis=0)
print(result2)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18]])]


**Easy Method**

**np.vsplit(array,number of sub-array):** Splits the array vertically (along rows for 2D arrays).

In [ ]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
result = np.split(arr2D, 2,axis=0)  # Split into 2 sub-arrays along raws
print(result)
# Output: [array([[1, 2, 3]]), array([[4, 5, 6]])]

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [ ]:
arr2D = np.array([[1, 2, 3,4,5,6], [7,8,9,10,11,12],[13,14,15,16,17,18]])
result2=np.vsplit(arr2D,3)# split array into 3 sub-array along raws
#print(result2)
# split 1st two raws , all columns of array  into 2 sub_array along raws
result3=np.vsplit(arr2D[0:2],2)
print(result3)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]


Note: number of raws of arr2D=3

number of sub-array=3

number of raws of each sub-array=3/3=1



**RULE:**  numbers of sub-arrays must divide numbers of raws of main- array

**4:
Transposing Arrays**

Transpose: convert raws into columns OR columns into raws
np.transpose() or .T is used for transposing.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr=np.transpose(arr)
print(transposed_arr)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]


[[1 4]
 [2 5]
 [3 6]]


**Using .T (shortcut):**

In [ ]:
transposed_arr=arr.T
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


**5:
Adding and Removing Elements :**

**For 1D:**

Adding Elements :

np.append(): Adds elements to the end of an array.

In [ ]:
arr = np.array([1, 2, 3])
result=np.append(arr,4)# add 4 at the end of array
#print(result)#Output: [1 2 3 4 ]
result2=np.append(arr,[4,5])# add 4,5 at the end of array
#print(result2)  # Output: [1 2 3 4 5]


**np.insert(): Inserts values at specified positions in the array.**

In [ ]:
arr = np.array([1, 2, 3])
result=np.insert(arr,1,10) # insert 10 at index 1
print(result)

[ 1 10  2  3]


**Removing Elements:**

np.delete(): Removes elements from an array at a given index.

In [ ]:
result=np.delete(arr,1) # delete element at index 1
print(result)

[1 3]


**For 2D:**

**Adding  new raws  to 2D array**

 np.append() method : add at the end of array

In [ ]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
result=np.append(arr2D,[[7,8,9],[10,11,12]],axis=0)# add two raws at the end of array
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**np.insert(): Inserts raws at specified positions in the array.**

In [ ]:
result=np.insert(arr2D,1,[[7,8,9],[10,11,12]],axis=0) # insert two raws at index 1
#print(result)
result2=np.insert(arr2D,[0,2],[[7,8,9],[10,11,12]],axis=0) # insert raw 1 at index 0 and raw 2 at index 2
print(result2)

[[ 7  8  9]
 [ 1  2  3]
 [ 4  5  6]
 [10 11 12]]


**Removing raws:**

np.delete(): Removes raw  from an array at a given index.

In [ ]:
result=np.delete(arr2D,1,axis=0) # delete raw at index 1
print(result)

[[1 2 3]]


**Adding new columns to 2D array**

np.append() method : add at the end of array

In [ ]:
result2=np.append(arr2D,[[1,3],[2,4]],axis=1) # add two columns at the end of array
print(result2)

[[1 2 3 1 3]
 [4 5 6 2 4]]


**np.insert(): Inserts columns at specified positions in the array.**

In [ ]:
result=np.insert(arr2D,1,[[7,8],[9,10]],axis=1) # add two columns at index 1
print(result)

[[ 1  7  9  2  3]
 [ 4  8 10  5  6]]


In [ ]:
result=np.insert(arr2D,[0,2],[[7,8],[9,10]],axis=1) # insert 1st column at index 0 and 2nd column at index 2
print(result)

[[ 7  1  2  8  3]
 [ 9  4  5 10  6]]


**Removing columns:**

np.delete(): Removes columns from an array at a given index.

In [ ]:
result=np.delete(arr2D,1,axis=1) # delete column at index 1
print(result)

[[1 3]
 [4 6]]


# Advanced NumPy Functions

In this section, we'll cover some of the more advanced features of NumPy, including broadcasting and vectorization

**1: Broadcasting**

**What is Broadcasting?**


Broadcasting is a powerful feature in NumPy that allows arrays of different shapes to be used together in arithmetic operations. When operating on two arrays, NumPy will automatically "broadcast" the smaller array across the larger one to make their shapes compatible.


B**asic Example of Broadcasting:**

When you add a scalar to an array, NumPy broadcasts the scalar to the shape of the array.

In [ ]:
arr = np.array([1, 2, 3])
result = arr + 5  # Scalar broadcast
print(result)  # Output: [6 7 8]
result2=arr**2
print(result2) # output:[1 4 9]


[6 7 8]
[1 4 9]


In [ ]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print("Original:", arr)
print("Times 2:", arr * 2)# multiplies each element by 2
print("Plus 5:", arr + 5)# adds 5 to each element
print("Squared:", arr ** 2)# squares each element


Original: [[1 2 3]
 [4 5 6]]
Times 2: [[ 2  4  6]
 [ 8 10 12]]
Plus 5: [[ 6  7  8]
 [ 9 10 11]]
Squared: [[ 1  4  9]
 [16 25 36]]


**Example with Arrays of Different Shapes:**

When adding a 2D array to a 1D array, NumPy will broadcast the 1D array along the rows or columns of the 2D array to make the shapes compatible.

In [ ]:
arr2D = np.array([[1, 2], [3, 4], [5, 6]])
arr1D = np.array([10,20])
# Broadcasting the 1D array to match the shape of the 2D array
result=arr1D+arr2D # arr1D add with each raw of arr2D
print(result)

[[11 22]
 [13 24]
 [15 26]]


**Rule:** Number of columns in 2D array = number of elements in 1D array

**Note:** it work same for all arthimatic operations (+,-,/,*)

**2: Vectorization(element-wise operation)**

Instead of looping over array elements, you can perform element-wise operations directly on the arrays:

**Vectorization Example:**

In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
result = arr1 * arr2  # Element-wise multiplication
print(result)  # Output: [ 5 12 21 32]


[ 5 12 21 32]


Efficiency of Vectorization:

Vectorized operations are much faster than using loops in Python because NumPy uses highly optimized C code behind the scenes.

#  np.random Module:

**np.random Module:** NumPy has a submodule np.random that provides a wide range of functions to generate random numbers.

**Random Number Generation:**

**Random Floats:** Generate random numbers between 0 and 1

> np.random.rand(size)



In [ ]:
print(np.random.rand()) # single number
print(np.random.rand(3)) # 3 random  numbers (1D array)
print(np.random.rand(3,2)) # 3x2 array of random number (2D array)
print(np.random.rand(3,2,2)) # 3x2x2 array of random number (3D array)
#random_floats = np.random.rand(3, 3)  # 3x3 array of random floats
#print(random_floats)


0.30206050183479505
[0.73195807 0.85117426 0.67142467]
[[0.80952998 0.76665614]
 [0.14970397 0.42394481]
 [0.1529838  0.23523558]]
[[[0.86925962 0.47289197]
  [0.5353581  0.17844597]]

 [[0.31227179 0.23024617]
  [0.20618616 0.63796079]]

 [[0.25688385 0.63201549]
  [0.05845461 0.14177439]]]


**Random Integers:** Generate random integers within a specified range.



> np.random.randint(low, high, size)



In [ ]:
print(np.random.randint(1,10)) # single random integer between 1 and 10
print(np.random.randint(1,10,5)) # 5 random integer between 1 and 10 (1D array)
print(np.random.randint(1,10,(2,3))) # 2x3 array of random integers between 1 and 10 (1D array)
#random_ints = np.random.randint(1, 10, size=(3, 3))  #3x3 array of  Random integers between 1 and 10
#print(random_ints)


3
[7 5 2 3 6]
[[7 9 1]
 [7 8 3]]


**Random Sample from a Given Array:** pick random elements from a list/array.



> np.random.choice()



In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.random.choice(arr)) # choice a single number randomly from arr
print(np.random.choice(arr,3)) # choice 3 numbers randomly from arr
print(np.random.choice(arr,20)) # choice 20 numbers randomly from arr

4
[2 2 5]
[4 5 1 4 3 1 1 3 1 4 5 1 4 2 4 5 4 3 5 2]


**Shuffling:** Randomly rearrange elements(1D) ,raws (2D) of orignal array in-place.


> np.random.shuffle()





In [ ]:
#arr=np.array([1,2,3,4,5])
#np.random.shuffle(arr) #  rendomly rearrange elements of arr
#print(arr)
arr2D = np.array([[4,5],[6,7],[8,9],[10,11]])
np.random.shuffle(arr2D)# rendomly rearrange raws of arr2D
print(arr2D)

[[ 4  5]
 [10 11]
 [ 6  7]
 [ 8  9]]


**Returns a new shuffled copy (original stays same).**

> np.random.permutation()





In [ ]:
arr2D = np.array([[4,5],[6,7],[8,9],[10,11]])
shuffled_arr=np.random.permutation(arr2D) # make a shuffled copy
print(shuffled_arr)
print(arr2D) # original stay same:
 #[[ 4  5]
 #[ 6  7]
 #[ 8  9]
 #[10 11]]

[[ 8  9]
 [10 11]
 [ 6  7]
 [ 4  5]]
[[ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


**Random Seeds:** If we want the same random numbers every time, set a seed.

> np.random.seed()



In [ ]:
np.random.seed(42)  # Set the seed
random_ints = np.random.randint(1, 10, size=(3, 3))  #3x3 array of  Random integers between 1 and 10
print(random_ints)

[[7 4 8]
 [5 7 3]
 [7 8 5]]


In [ ]:
np.random.seed(42) # set a seed
arr=np.array([1,2,3,4,5])
np.random.shuffle(arr)
print(arr)

[2 5 3 1 4]


we set a seed(42) so it rearrange the array randomly one time  and every time we run the code it give the  same randomly rearranged  array at seed(42)

**Random Distributions in NumPy(smart guess)**



> np.random.distribution(parameters, size)

**Normal Distribution:** (smartly guess  number near to average)

Human heights → most people are near average, few are very tall/short → normal distribution.

> np.random.normal(mean,std,size)

mean → average

std → spread (standard deviation)

size → number of samples

In [ ]:
np.random.normal(1,2,5) # smartly guess 5 number near to mean=1 (std =2)
np.random.normal(1,2,(2,3)) # smartly guess 2x3 array  (elements should be near to mean= '1' and std =2

array([[ 0.01439315,  1.7851595 , -0.85836933],
       [ 1.15966362,  0.680967  ,  1.04444365]])

In [ ]:
# smartly guess 1000 random heights around a mean of 170 and standard deviation of 10
heights=np.random.normal(170,10,1000)
#print(heights)

Note: every random number in normal distribution are around mean and standard daviation


> np.random.randn(size)



In [ ]:
normal_dist = np.random.randn(3, 3)  # 3x3 array of random numbers from standard normal distribution
print(normal_dist)



[[ 0.55935921 -0.33541214  2.41339392]
 [ 0.65140928  1.97654427  1.35147843]
 [ 0.46413466 -0.57970091 -0.02410488]]


**Uniform Distribution (The "Fair Game")**

Now, imagine you're rolling a fair die. Every number, from 1 to 6, has the exact same chance of landing. This is an example of a uniform distribution (probability remain same)

every outcome within a range of possible outcomes has a equal chance of happening

> np.random.uniform(min,max,size)



In [ ]:
# Randomly pick 10 outcomes from a fair die (numbers 1 to 6)
die_rolls=np.random.uniform(1,7,10)
print(die_rolls)
#

[1.98399689 3.6316433  5.34895936 4.55967189 4.90176512 3.87567357
 4.69445213 2.97410463 3.82109556 5.46567439]


In [ ]:
# generate random 2x3 array of uniformly distributed(number from 1 to 9)
arr=np.random.uniform(1,10,(2,3))
print(arr)


[[8.84649501 4.90289801 1.39295492]
 [2.4550529  1.18775025 6.87936717]]


In [ ]:
np.random.uniform(1,12,(2,3))

array([[4.65546088, 6.96726499, 6.42604531],
       [1.89679139, 5.43587497, 3.42617237]])

**Binomial Distribution:**

**Bernoulli trial**

A single event that can only have two outcomes:
Success or Failure.

example: boundry in one ball

So each ball is a Bernoulli trial.

**Binomial experiment(trail)**

**repeatetion of bernoulli trals a fixed number of times = 1 binomial experiment**

then count how many successes  you got out of those bernouli trails

**example:** boundaries in 6 balls =1 over is a  binomial experiment

Each ball is independent(The result of one ball has no effect on the next ball.)



**Binomial distribution**

**repeatation of binomial experiment**

> np.random.binomial(number of bernouli trails,probability,number of repeating binomial experimen)

 probabilty of success(getting head) is constant for each bernoulli trail




In [ ]:
# 6 Bernoulli trials(one over)  in each binomial experiment
# Probability of success(boundary) = 0.5
# Repeat the binomial experiment 20times
np.random.binomial(6,0.5,20)


array([3, 2, 4, 2, 5, 3, 4, 3, 4, 4, 3, 3, 3, 3, 1, 3, 3, 3, 4, 3])

**Real life example**

Let we want see cricket team's boundries(6 or 4) per over (In a T-20 match )

one ball= a bernoulli trail(two outcomes:boundrie= "yes" or "no")

one over=6 balls is a binomial experiment

we know that there are 20 over per match in T-20 match

we need to repeat binomial experiment 20 times

suppose probabilty of hit boundary per ball =0.25

**here we use random madule's binomial distribution**

In [ ]:
boundries_per_over=np.random.binomial(6,0.25,20)
print(boundries_per_over)

[4 1 1 1 1 3 1 2 1 2 2 1 1 1 0 1 0 1 2 2]


In [ ]:
# Perform 100 binomial trials of flipping a fair coin 10 times
# outcomes of each binomial experiment (1 binomial experimet =10 bernoulli trails(10 flips))
#
flip=np.random.binomial(10,0.5,100)
print(flip)


[6 3 6 4 5 7 1 5 5 5 4 4 7 5 4 5 6 3 5 5 8 4 4 5 5 4 5 6 6 5 7 5 5 2 8 3 4
 2 6 4 4 3 3 5 6 5 5 6 2 4 8 5 4 5 4 5 3 3 3 7 6 3 4 6 3 4 8 4 6 8 4 2 4 7
 7 6 3 6 7 5 7 6 6 5 4 3 5 4 7 9 6 3 4 3 6 6 7 5 7 7]


**poisson distribution**

 "When we know the average number of times an event happens in an interval(a minute, an hour, a square meter), you can use numpy.random.poisson() to simulate(smart guess) how many times that event might randomly happen in a future interval."

> np.random.poisson(lam,size)



*   lem=lembda=average rate

**Real Life example:**


Imagine we're right here at the Multan stadium, watching the match live. Abdullah is batting, and we need a plan.

From looking at all his past games, we know one simple thing: Abdullah usually hits about 3 boundaries per over. That's just his normal style.

So, we need smart guess. what might happen in the next 5 overs he's about to face?

We can use a computer(np.random.poisson()) to help us guess. We tell the computer, "Abdullah's normal is 3 boundaries an over."

Then, the computer creates a pretend story for us, showing one possible way the next 5 overs could go. It might show him hitting 1 boundary, then 3, then 0, then 4, then 2.

It’s a smart guess that helps the captain plan for what could happen next,
all based on what Abdullah usually does.

In [ ]:
import numpy as np
# abdullah's average number of boundaries per over
avg_boundries_per_over=3
#randomly smart guess how many boundries hit in next over on the base of average rate =3
boundries_in_next_over=np.random.poisson(3)
print(boundries_in_next_over)
# randomly smart guess boundries (boundries per over) for next 5 over
boundries_per_over=np.random.poisson(3,5)# guess boundries for next 5 over on base of average rate =3
print(boundries_per_over)

3
[4 4 0 3 6]


**The Problem:** The manager of a popular website knows that, on average, they get 50 new customers signing up every hour. But this is just an average! In one hour, they might get 45, and in the next, they might get 62.

**The Question:** The manager wants to test their computer systems. . Can their system handle the traffic.He want to see trafic per hour for next 24 hour

In [ ]:
# The one thing we know for sure: the average sign-ups per hour
avg_signups_per_hour =50
# randomly smart guess how many signup for next hour
signup_in_next_hour=np.random.poisson(avg_signups_per_hour)
print(signup_in_next_hour)
# randomly smart guess how many signup for next 24 hour
signup_per_hour=np.random.poisson(avg_signups_per_hour,24)
print(signup_per_hour)


41
[44 48 55 50 48 53 43 43 52 51 38 48 58 57 46 43 48 57 50 50 57 42 61 51]


company can now use this data to test if their servers would crash during that "busiest hour" you found.

# Linear Algebra Functions

**Vector:** A vector is a list of numbers arranged in a single row(1D array) or a single column.

 **Matrix (2D Array):** A table of numbers with rows and columns.

**$Core Matrix And Vector Operations$**

**1-----Vector multiplication with np.dot():**



**Dot product of two vectors(1D array):( np.dot(arr1,arr2))**

multiplies corresponding elements of two  vectors(1D arrays) and then adds them all up


In [ ]:
import numpy as np

arr1 = np.array([2, 3, 1])
arr2 = np.array([300,150,100])
dot_product=np.dot(arr1,arr2)
print(dot_product) #output=1150


1150


The calculation it performed was: (2 * 300) + (3 * 150) + (1 * 100) = 600 + 450 + 100 = 1150.

**Rule:** number of elements must be equall in both 1D arrays (vectors)

**2-----matrix-vector multiplication. with np.dot() method**

**Dot product of  matrix (2D array) with vector(1D array):** dot product of each row of matrix with vector

In [ ]:
import numpy as np

matrix = np.array([
    [2, 3, 1],
    [5, 2, 2],
    [4, 1, 3]
])

vector = np.array([300, 150, 100])
np.dot(matrix,vector) # each raw of matrix dot product with vector  output:[1150, 2000, 1650]


array([1150, 2000, 1650])

**Rule:** number of elements in each raw=number of elements in vector

**Dot product of two matrices(2D arrays ):**

each raw of matrix1 dot product with each column of matrix2

In [ ]:
matrix1 = np.array([
    [10, 18, 25],
    [15, 12, 22],
    [ 8, 20, 30]])
matrix2=np.array([
    [25, 10],
    [15,  7],
    [ 3,  1] ])
dot_product=np.dot(matrix1,matrix2)
print(dot_product)

[[595 251]
 [621 256]
 [590 250]]


**Rule** number of columns in matrix1=number of raw in matrix2

**3========Most powerfull method for multiplications**


> np.matmul(arr1,arr2) OR arr1 @ arr2 ("@" use for matrix multiplicatuion)

**4------Vector multiplication with np.matmul() "@" method:** Dot product of two vectors(1D array)

multiplies corresponding elements of two vectors(1D arrays) and then adds them all up

In [ ]:
arr1 = np.array([2, 3, 1])
arr2 = np.array([300,150,100])
dot_product=arr1@arr2
print(dot_product) #output=1150

1150


The calculation it performed was: (2 * 300) + (3 * 150) + (1 * 100) = 600 + 450 + 100 = 1150.

**Rule:** number of elements must be equall in both 1D arrays (vectors)

**5------ matrix-vector multiplication. with np.matmul() "@":**

Dot product of matrix (2D array) with vector(1D array): dot product of each row of matrix with vector

In [ ]:
import numpy as np

matrix = np.array([
    [2, 3, 1],
    [5, 2, 2],
    [4, 1, 3]
])

vector = np.array([300, 150, 100])
matrix_multiplication=matrix@vector # OR np.matmul(matrix,vector)
print(matrix_multiplication)# output:[1150, 2000, 1650]


[1150 2000 1650]


**Rule:** number of elements in each raw=number of elements in vector

**Dot product of two matrices(2D arrays ):**

each raw of matrix1 dot product with each column of matrix2

In [ ]:
matrix1 = np.array([
    [10, 18, 25],
    [15, 12, 22],
    [ 8, 20, 30]])
matrix2=np.array([
    [25, 10],
    [15,  7],
    [ 3,  1] ])
matrix_multiplication=np.matmul(matrix1,matrix2)
print(matrix_multiplication)

[[595 251]
 [621 256]
 [590 250]]


**Rule** number of columns in matrix1=number of raw in matrix2

**Note:** **matrix multiplication is not commutative.(the order of multiplication matters)**

 np.dot(matrix,vector) and np.dot(vector,matrix) are not eqaull

 matrix@vector and vector@matrix are not equall

 np.matmul(matrix,vector) and np.mulmat(vector,matrix )
 are not equall

 np.matmul(matrix1,matrix2) and  np.matmul(matrix2,matrix1) are not equall

**For vectors multiplication we offten use np.dot() method**

**for matrices we use np.matmul() "@" method**

**Why is this a data science superpower?** 🦸‍♂️ Almost every machine learning model, from the simplest linear regression to the most complex neural network, is essentially doing a series of dot products. It's how models calculate weighted sums to make predictions.

**$Vector And Matrix Norms$**


> np.linalg.norm(vector)



 Imagine you're standing at the center of a map (point 0,0). A treasure is buried at the coordinates (3, 4). How would you measure the straight-line distance to that treasure?You'd use the Pythagorean theorem: $\sqrt{3^2 + 4^2} = \sqrt{9 + 16} = \sqrt{25} = 5$.This "distance" or "magnitude" is exactly what a vector norm calculates. It tells you the "size" of a vector. In NumPy, you use np.linalg.norm().

In [ ]:
treasure_location=np.array([3,4])
distance=np.linalg.norm(treasure_location)
print(distance)

5.0


**Why is this a data science superpower?** It's used everywhere to measure error. If your model's prediction is a vector and the actual truth is another vector, the norm of their difference tells you how "far off" your prediction was. In algorithms like K-Nearest Neighbors (k-NN), it's used to find the "closest" data points. In regularization, it's used to keep the model's weights (the "prices" from our first story) small to prevent the model from becoming too complex and overfitting the data.

In [ ]:
model_prediction=np.array([2,3])
actual_vector=np.array([5,6])
difference=actual_vector-model_prediction
#the norm of their difference tells you how "far off" your prediction was.
error=np.linalg.norm(difference)
print(error)

4.242640687119285


**$Flipping Your Data Table: Transpose$**



> matrix.T OR np.transpose(matrix)

transpose (.T) simply flips the rows and columns. It's like rotating the table.

change raws into column OR columns into raws

In [ ]:
matrix = np.array([
    [90, 85],
    [75, 82]])
matrix_transpose= matrix.T # OR np.transpose(matrix)
print(matrix_transpose)


[[90 75]
 [85 82]]


**Why is this a data science superpower?** It's the simplest and most common way to reshape your data. Many mathematical formulas and library implementations expect data to be in a specific orientation (e.g., features as columns). The transpose is your go-to tool for making sure your data "fits" the algorithm you're using.

**$The Stretching Factor: Determinant$**



> np.linalg.det(matrix)

**The identity matrix**($I$) is a special square matrix that has 1s on the main diagonal and 0s everywhere else. It's the matrix equivalent of the number 1.

$$I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}$$

Imagine you have a piece of special graph paper where you've drawn identity (I) matrix and you got a perfect 1x1 square . This square  has an area of 1.

**linear transformation(function): 1st define a linear transformation  (T=A) then perform this transformation to identity matrix(T(I)=A.I) after that you got a new matrix(T(I)=A.I=B) and when you draw new matrix(B) on graph paper you got a new shape , usuallya parallelogram.**

**NOTE:** a matrix itself a linear transformation(function)

The **determinant** is a single, magic number that tells you the area of this new parallelogram. It measures the "stretching factor" of the transformation.

If the determinant is 2, it means  the new shape has an area of 2. The area doubled.

If the determinant is 0.5, the new shape's area is 0.5. The area was halved.

If the determinant is -1, it means the area is still 1, but the transformation also "flipped" the orientation of the space (like looking at it in a mirror).

It also tell us about data spreadness

Deteminant is 2, means data 2 time stretch

Deteminant is 0.5 ,mean data is shrunk half

In [ ]:
# let you have  new parallelogram (matrix)
matrix= np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

determinant=np.linalg.det(matrix)
print(determinant)

0.0


**The most important case for data science:** What if the determinant is 0? This means the machine completely flattened your square into a single line. The area of a line is zero! You've lost a dimension—you can no longer tell it was a square.

$Matrix Inverse:$


A matrix $A$ is a function that transforms a vector $v$ into a new vector $w$.

$w = A \cdot v$

The inverse matrix $A^{-1}$ is the function that reverses this transformation, turning $w$ back into $v$.

$v = A^{-1} \cdot w$

> np.linalg.inv(matrix)

 **linear algebra**, the inverse of a matrix $A$ is another matrix, written as $A^{-1}$, such that when you multiply them together, you get the identity matrix ($I$).

 $$A \cdot A^{-1} = A^{-1} \cdot A = I$$

 In NumPy, the ***np.linalg.inv()*** function computes the inverse of a given matrix.

In [ ]:
matrix= np.array([
    [4, 7],
    [2, 6]])
matrix_inverse=np.linalg.inv(matrix)
print(matrix_inverse)

[[ 0.6 -0.7]
 [-0.2  0.4]]


**Rule:**  determinant of matrix must be non-zero

***Solve a system of linear equations (like the $Ax = b$ problem)***

**1st method:**

In math, we know we're solving for $x$ in the equation $Ax = b$.

Since we've already covered **np.linalg.inv()**

 we know one way to solve this is by finding the inverse of A and then multiplying it by b:x= inverse of A x b

 Let's try it with a simple 2x2 system:

$3x + 1y = 9$

$1x + 2y = 8$

create the matrix A and the vector b for our system in numpy by np.array() method

In [ ]:
A=np.array([[3,1],[1,2]])
b=np.array([9,8])
# inverse of A
inverse_of_A=np.linalg.inv(A)
# solve system by x= inverse of A x b
x=inverse_of_A@b
print(x)

[2. 3.]


When you run that code, print(x) will output:[2. 3.]This means $x = 2$ and $y = 3$.

**2nd Method :**

NumPy provides a much more efficient and numerically stable function called

> np.linalg.solve(matrix, vector)



In [ ]:
x=np.linalg.solve(A,b)
print(x)

[2. 3.]


When you run that code, print(x) will output:[2. 3.]This means $x = 2$ and $y = 3$.



**Real Life example for system of equation:**

Let's use a simple shopping problem.

Imagine you go to a market and buy:

Day 1: 2 apples and 3 bananas, which costs 8

Day 2: 4 apples and 1 banana, which costs $9.

We want to find the price of a single apple ($x$) and a single banana ($y$).This gives us two equations:

$2x + 3y = 8$

$4x + 1y = 9$

we can solve it by

**Inverse Method:** x = np.linalg.inv(A) @ b (Good for understanding the math)

**Solve Method:** x = np.linalg.solve(A, b) (Preferred in practice for speed and stability)

$Eigenvalues And Eigenvectors.$

**Eigenvector:**

Think of a matrix $A$ as a linear transformation. When you apply this transformation to a vector, it usually gets rotated and stretched, pointing in a completely new direction.

**An eigenvector** is a special, non-zero vector $v$ that, when you apply the transformation $A$ to it, does not change its direction. It only gets stretched, shrunk, or flipped.

**Eigenvalue**

The eigenvalue (represented by $\lambda$, or lambda) is the scalar factor that tells you how much the eigenvector was stretched, shrunk, or flipped.

If $\lambda = 2$, the eigenvector $v$ is doubled in length.

If $\lambda = 0.5$, the eigenvector $v$ is halved.

If $\lambda = -1$, the eigenvector $v$ is flipped and points in the exact opposite direction.

**The next major topic from numpy.linalg is finding eigenvalues and eigenvectors of a matrix.**

these are the special vectors $v$ and scalars $\lambda$ that satisfy the equation $Av = \lambda v$.

> np.linalg.eig(A)

This function returns two things:

1.  An array of eigenvalues ($\lambda$).
2. A matrix where the columns are the corresponding eigenvectors ($v$).

**Example:** Let's use a simple 2x2 matrix:
$A = \begin{bmatrix} 4 & 2 \\ 1 & 3 \end{bmatrix}$

In [ ]:
A = np.array([[4, 2],
              [1, 3]])

# Calculate eigenvalues and eigenvectors
# np.linalg.eig() returns *two* things:
# 1. a list of eigenvalues
# 2. a matrix of eigenvectors
# We need to assign them to two variables
eigenvalues,eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


**Verification**

We can easily check if the math $Av = \lambda v$ holds true. Let's check for the first eigenvalue/eigenvector pair.

In [ ]:
v1=eigenvectors[:,0]
lambda1=eigenvalues[0]
print("A.V1:",A@v1)

print("lambda1.v1:\n",lambda1*v1)

A.V1: [4.47213595 2.23606798]
lambda1.v1:
 [4.47213595 2.23606798]


**Singular Value Decomposition(SVD):** A mathematical method that factors a matrix(A) into three other matrices(U,S, V^T) this is written as: A = U * S * V^T
> np.linalg.svd()

It takes our big, complicated matrix (Data) and breaks it down into three simpler, more useful parts (U,S,V^T).

**U -** This Orthognal matrix(columns vector are perpendicular to each other and length of each column=1) tells us something about the rows of our data. If our data was about kids rating movies, U would describe the kids. For example, it might find a "pattern" or "design" for kids who love action movies and another pattern for kids who love comedies.

**s -** The Importance Scores: This is the most special part! It's  just a simple list of numbers, sorted from biggest to smallest. These numbers are called singular values. They tell us the "strength" or "importance" of each pattern. The first number is the strength of the most important pattern, the second number is for the second most important, and so on. This is our list of importance scores.

**Vt -** This Orthognal  matrix tells us something  about the columns of our data. If our data was kids rating movies, Vt would describe the movies. It might find a "pattern" for big blockbuster movies and another for quiet indie films..

SVD is like having X-ray vision for your data. It lets you break down something complicated into its simple, most important building blocks, so you can understand it better and make smarter decisions.

In [ ]:
A=np.array([[3,0],[4,5]])
u,s,v_t=np.linalg.svd(A)
a=u@s@v_t
print(a)

[ 7. -1.]


# File Input/Output (I/O)

**File Output(saving):**


> np.save(filename, array):

Saves a single array to a file(in computer). NumPy will automatically add the .npy extension. it saves the data in a special binary format(.npy) that only NumPy  understands.


In [ ]:
# 1. Create an array (our "work")
my_grade=np.array([95,80,90,69,93])
print(my_grade)
# 2. Save it  to a file(in computer)
np.save("My_Grade",my_grade)

[95 80 90 69 93]


**File Input(loading):**


> np.load(filename):Loads your array from a file



In [ ]:
# 3. Load it back
loaded_grade=np.load("My_Grade.npy")
print(loaded_grade)

[95 80 90 69 93]


**Practice Question 1:** Create a 2D array (a 3x3 matrix) of your favorite numbers. Save it to a file called my_matrix.npy and then load it back into a new variable called reloaded_matrix.

In [ ]:
my_matrix=np.arange(9).reshape(3,3)
print(my_matrix)
# save it to file
np.save("my_matrix",my_matrix)
# load into program
reloaded_matrix=np.load("my_matrix.npy")
print(reloaded_matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Real-World Application:** You've just spent 3 hours training a Machine Learning model. The "weights" (parameters) of your model are stored in a large NumPy array. You use np.save() to save those weights so you don't have to re-train the model every time.

**saveing multiple array togather**


What if you have multiple arrays you want to save together?
> np.savez(filename, name1=array1, name2=array2):

 Saves multiple arrays. You must give each array a "keyword" name (like name1, name2). Numpy automatically add .npz extention
>  np.load(filename):

  Loads the file. You then access the arrays inside like a Python dictionary, using the names you gave them.

In [ ]:
# 1. Create multiple arrays
student_ids = np.array([101, 102, 103])
final_scores = np.array([89.5, 92.0, 78.5])
# 2. Save them together in one .npz file
# We name them 'ids' and 'scores' inside the file
np.savez("student_data", ids=student_ids,scores=final_scores)
# 3. Load the .npz file
student_data=np.load("student_data.npz")
# 4. now we can Access the arrays by their names
print(student_data["ids"])
print(student_data["scores"])
# You can see all the names (keys) like this:
list(student_data.keys())

[101 102 103]
[89.5 92.  78.5]


['ids', 'scores']

**Practice Question 2**: Create two arrays: sales_q1 (e.g., [100, 150, 120]) and sales_q2 (e.g., [110, 130, 180]). Save them both to a single file named all_sales.npz. Then, load the file and print only the sales_q2 array.

In [ ]:
sales_q1=np.array([100, 150, 120])
sales_q2=np.array( [110, 130, 180])
np.savez("all_sales",q1=sales_q1,q2=sales_q1)
# 3. Load the .npz file
all_sales=np.load("all_sales.npz")
# You can see all the names (keys) like this:
list(all_sales.keys())
# print only the sales_q2 array.
print(all_sales["q2"])

[100 150 120]


**.npy / .npz:**

 Very fast, small file size, preserves data types perfectly.

 Not human-readable. Only Python/NumPy can use it.

Use: Saving your own work, intermediate calculations, model weights.

**Saving array as a text file**

The function we use is np.savetxt because we are, fundamentally, saving array as a text file.

> **np.savetxt('filename.csv', my_array, delimiter=',')**

This tells NumPy: "Save my_array as a text file. Separate all the values with a comma".


**The delimiter is crucial**—it's the character that separates the numbers. For CSVs, it's a comma (,).

Note: Adding the .csv extension is not strictly necessary, but it is highly recommended and important for other programs (like Excel) to automatically recognize the file format."


> **np.savetxt('filename.txt', my_array, delimiter='\t')**



This tells NumPy: "Save my_arrayas a text file. Separate all the values with a Tab."

This creates a .tsv (Tab-Separated Values) file, which is another common format.



> **np.savetxt('filename.txt', my_array, delimiter=' ')**



This tells NumPy: "Save my_array as a text file. Separate all the values with a space."

The result is just a clean, space-separated text file.

**np.savetxt** is not smart and will not add any extension by default


> np.loadtxt(filename. extension , delimiter=?):

Loads data from a text file. You must tell it what the delimiter is. For.csv its comma ","  

space/tab are default delimter

In [ ]:
# 1. Create a 2D array (like a spreadsheet)
# This data could be [temp, humidity, pressure]
weather_data = np.array([
    [15.2, 65, 101.2],
    [16.1, 68, 101.1],
    [14.9, 62, 101.5]])
# 2. Save it as a CSV file
# We'll use a comma as the separator
np.savetxt("weather_data.csv",weather_data,delimiter=",")
# 3. Load it back
# Note: This file 'weather.csv' can be opened perfectly in Excel!
np.loadtxt("weather_data.csv",delimiter=",")

array([[ 15.2,  65. , 101.2],
       [ 16.1,  68. , 101.1],
       [ 14.9,  62. , 101.5]])

**Note:**

1-np.savetxt is designed to save only one array at a time.

2-pd.read_csv() is much more flexible than np.loadtxt(). Pandas is designed to handle messy, real-world CSVs with text headers, missing values, and mixed data types.

**Rule**

If your data is purely numerical (a big matrix) and you need to load it into a NumPy array, np.loadtxt() is simple and fast.

If your data is a typical dataset (has column names, text, numbers, missing values), use Pandas pd.read_csv() first, and then get the NumPy array from the DataFrame if you need it (e.g., my_dataframe.values).

**Practice Question 3:**
 You have a 2x3 array representing [latitude, longitude, elevation] for two locations. locations = np.array([[40.7128, -74.0060, 10], [34.0522, -118.2437, 71]]) Save this array to a file named locations.txt using a tab as the delimiter (hint: the tab delimiter is '\t'). Then, load it back.

In [ ]:
locations=np.array([[40.7128, -74.0060, 10], [34.0522, -118.2437, 71]])
np.savetxt("locations.txt",locations,delimiter="\t")
np.loadtxt("locations.txt",delimiter="\t")

array([[  40.7128,  -74.006 ,   10.    ],
       [  34.0522, -118.2437,   71.    ]])

**.txt / .csv:**

 Human-readable! Can be opened by any program (Excel, R, Pandas, text editors).

 Much larger files, slower to load/save, can lose precision (e.g., $1/3$ becomes $0.333333$). np.loadtxt can be fussy and often fails if there's any text (like headers) or missing values.

Use: Sharing data with colleagues, exporting results for a report, loading a simple dataset from the web.

**We've covered saving single arrays, multiple arrays, and human-readable text files.**

# Handling Missing Values

**What Is a Missing Value? (np.nan):**

magine you're giving a survey to 10 people. You ask for their age.

9 people fill it in.

1 person leaves the "age" question blank.

When you collect this data in your NumPy array you put "np.nan" at 10 spot (blank place )  
**np.nan** stand for not a number which mean **"we don't know"**

You can't put 0, because 0 is a valid age (for a newborn).

You can't just leave it empty, because a NumPy array must be a complete grid.

**Let create an array with missing value(np.nan)**

In [ ]:
import numpy as np

# Sensor readings for temperature
# The last sensor failed to report.
temps = np.array([20.1, 22.5, 19.8, np.nan])

print(temps)

[20.1 22.5 19.8  nan]


**Remimber 1:** np.nan is a float (the number (np.nan) that we don't know is a float data type)

If you try to add np.nan to an array of integers, NumPy will automatically convert the entire array to floats to accommodate it.(numpy's upcasting nature)

In [ ]:
# An array of integers
int_array = np.array([1, 2, 3])
print(f"integer array:{int_array}  Type:{int_array.dtype}") #integer array:[1 2 3]  Type:int64
# An array with a missing value
nan_array = np.array([1, 2, 3,np.nan])
print(f"nan_array:{nan_array}  Type:{nan_array.dtype}") # nan_array:[ 1.  2.  3. nan]  Type:float64

integer array:[1 2 3]  Type:int64
nan_array:[ 1.  2.  3. nan]  Type:float64


**This is a core concept:** to have missing values, you'll almost always be working with float arrays.

**Remimber 2:** Our **nan** value "infected" all of our calculations

when you  do math with a np.nan value

5 + np.nan = nan

10 * np.nan = nan

**Analogy:** If I ask you to calculate (20 + 22 + 19 + "I don't know") / 4, you can't!. The "I don't know" breaks the entire calculation.

Let's see this in NumPy. Let's try to find the sum and  average of  temperature from our array:

In [ ]:
# Sensor readings for temperature
# The last sensor failed to report.
temps = np.array([20.1, 22.5, 19.8, np.nan])
print(f"Sum:{np.sum(temps)}  Average:{np.mean(temps)}") # Sum:nan  Average:nan

Sum:nan  Average:nan


**The Solution:** "NaN-Safe" Functions
NumPy  provides a set of functions that are "NaN-safe." They perform the calculation by **simply ignoring** the nan values

np.sum() -> np.nansum()

np.mean() -> np.nanmean()

np.min() -> np.nanmin()

np.max() -> np.nanmax() ...and so on.

In [ ]:
temps = np.array([20.1, 22.5, 19.8, np.nan])

print(f"nan_safe Sum:{np.nansum(temps)} nan_safe Average:{np.nanmean(temps)}")
# nan values are ignored  output:Sum:62.400000000000006 Average:20.8

nan_safe Sum:62.400000000000006 nan_safe Average:20.8


You have an array of student scores on a test. One student was absent. scores = np.array([88.0, 92.5, np.nan, 76.0])

How would you find the highest score and the lowest score from the students who took the test?

In [ ]:
scores = np.array([88.0, 92.5, np.nan, 76.0])
print(f"highest_score:{np.nanmax(scores)}  Lowest_score:{np.nanmin(scores)}") # highest_score:92.5  Lowest_score:76.0

highest_score:92.5  Lowest_score:76.0


**To Find a nan value**


> np.isnan(array):it returns a boolean array of True / False values. (boolean mask)




In [ ]:
temps = np.array([20.1, 22.5, 19.8, np.nan])

# Ask "Is this value nan?" for every item
missing_mask=np.isnan(temps)
print(missing_mask) # output:[False False False  True]

[False False False  True]


**Example 1:** How many values are missing? Since True is treated as 1 and False as 0, we can just sum the mask!

In [ ]:
print(f"Total missing values: {np.sum(missing_mask)}") # Total missing values: 1

Total missing values: 1


**Example 2:** How do I replace the missing values? (Imputation)

This is a very common task called **imputation.** Let's say our policy is "if a sensor fails, just replace its value with 0."

We can use our missing_mask as an index.

In [ ]:
temps = np.array([20.1, 22.5, 19.8, np.nan])
print(f"Original: {temps}")

# Find the missing values
missing_mask = np.isnan(temps)

# Use the mask to select ONLY the missing items
# and set them to 0
temps[missing_mask]=0
print(f"After imputation: {temps}")

Original: [20.1 22.5 19.8  nan]
After imputation: [20.1 22.5 19.8  0. ]


**Practice Question (Level 3):**

Let's do a more advanced imputation. scores = np.array([80.0, 90.0, np.nan, 70.0])

Your task: Replace the np.nan value with the average of the other scores

In [ ]:
scores = np.array([80.0, 90.0, np.nan, 70.0])
# find nan values
missing_mask=np.isnan(scores)
# find nan_safe average
average_of_scores=np.nanmean(scores)
# replace na value with average of scores
scores[missing_mask]=average_of_scores
print(scores)

[80. 90. 80. 70.]


***Masked Arrays:***

**data:**

 The raw data (e.g.,age=np.array([10, 12, 9, -999, 8])) Here, -999 is a sentinel value or error code).

The problem is, -999 is a real number! If you calculate the average of ages, the -999 will ruin it.

**mask:** A boolean array saying which values to ignore or hide (e.g., [False, False, False, True, False])

NumPy has a special module for this: **numpy.ma** (Masked Array).

In [ ]:
import numpy.ma as ma

# Our data, where -999 means "missing"
ages_data = np.array([10, 12, 9, -999, 8])

# 1. Create the masked array
#    Tell it to mask (hide) all values that are == -999
masked_ages=ma.masked_where(ages_data==-999,ages_data)
print(f"Masked_array:{masked_ages}")
# 2. now  Do the calculation
print(f"Average:{np.mean(masked_ages)}")
print(f"Sum:{np.sum(masked_ages)}")
# OUTPUT
#Masked_array:[10 12 9 -- 8]
#Average:9.75
#Sum:39

Masked_array:[10 12 9 -- 8]
Average:9.75
Sum:39


The printout shows -- where the value is masked.

The average is (10 + 12 + 9 + 8) / 4 = 9.75. It correctly ignored the -999 without us having to use a special nan- function!

This is a cleaner, more powerful way to handle missing data, especially when your "missing" flag isn't np.nan.

# Sorting in numpy

**sorting:**

Imagine you have a pile of numbered blocks, all jumbled up: [7, 1, 5, 3].

**Sorting** is simply the process of arranging them in order, from smallest to largest: [1, 3, 5, 7].(accending order)

>**In NumPy, we use the np.sort() function.**


In [ ]:
import numpy as np
# Our jumbled blocks
arr=np.array([7,1,5,3])

# Let's sort them!
sorted_arr=np.sort(arr)
print(sorted_arr) # outtput: [1 3 5 7] (smallest to largest)

[1 3 5 7]


**Key Point:** np.sort()  doesn't change your original array. It gives you a new, sorted copy. Your original arr is still [7, 1, 5, 3].

**Practice Question:** If you have an array a = np.array([20, 10, 30]), what will np.sort(a) return?

In [ ]:
a = np.array([20, 10, 30])
b=np.sort(a)
print(b) # output: [10 20 30]

[10 20 30]


**sort method:**
Sometimes, you don't need a copy. You just want to sort your original array and save memory. For this, you use the .**sort()** method, which modifies the array directly.

In [ ]:
# Our messy array
arr = np.array([5, 1, 10, 2])

print("Original array:", arr)

# Sort it "in-place"
arr.sort()
print(f"after arr.sort():{arr}")

Original array: [ 5  1 10  2]
after arr.sort():[ 1  2  5 10]


**This time, arr itself has been changed.**

**Sorting 2D Arrays:**

**If your data in 2D array**

arr2d=

[[5, 1, 4],

 [2, 6, 3]]

This is controlled by the **axis** parameter.

**axis=1->** sort items of each row of 2D array (default)

([5, 1, 4] -> [1, 4, 5]) and ([2, 6, 3] -> [2, 3, 6]).

**axis=0->** sort items of each column of 2D array

([5, 2]) -> ([2, 5]) , ([1, 6]) ->  ([1, 6]) and ([4,3]) -> ([3,4])




In [ ]:
arr2D= np.array([
    [5, 1, 4],
    [2, 6, 3]
])
# 1. Sort along the rows
sorted_rows=np.sort(arr2D,axis=1)
print(sorted_rows)
# Output:
# [[1 4 5]  <- Row 1 is sorted
#  [2 3 6]] <- Row 2 is sorted


# 2. Sort along the columns
sorted_columns= np.sort(arr2D,axis=0)
print(sorted_columns)
# Output:
# [[2 1 3]  <- Column 1 (5, 2) became (2, 5)
#  [5 6 4]] <- Column 2 (1, 6) became (1, 6), etc.

[[1 4 5]
 [2 3 6]]
[[2 1 3]
 [5 6 4]]


**Practice Question:** Given b = np.array([[3, 1], [6, 2]]), sort b along column

In [ ]:
b = np.array([[3, 1], [6, 2]])
sorted_column=np.sort(b,axis=0)
print(sorted_column)

[[3 1]
 [6 2]]


**np.argsort():**

Instead of giving you the sorted data, **np.argsort()** gives you the indices (the positions) of the data in sorted order.

In [ ]:
arr2D= np.array([
    [5, 1, 4],
    [2, 6, 3]
])
# indices (position) of items of sorted array
sorted_indices=np.argsort(arr2D,axis=1)
print(sorted_indices)
#[[1 2 0] row1 -> smallest item at index 1 ,1st item at index 2 and the highest item at index 0
# [0 2 1]] row 2 -> smallest item at index 0 ,1st item at index 2 and highest item at index 1

[[1 2 0]
 [0 2 1]]


**Real-World Application:** This is essential for data science. Imagine you have an array of product_names and an array of sales. You can use np.argsort() on the sales array to get the indices, and then use those indices to reorder the product_names array to see your top-selling products.

In [ ]:
ages = np.array([25, 30, 18, 45])
names = np.array(["Sarah", "David", "Min", "Tom"])
# Get the indices that would sort the 'ages' array
sorted_indices=np.argsort(ages)
# Now, use these indices to sort both arrays
sorted_name=names[sorted_indices]
sorted_ages=ages[sorted_indices]
print(f"sorted_name:{sorted_name}")
print(f"sorted_ages:{sorted_ages}")



sorted_name:['Min' 'Sarah' 'David' 'Tom']
sorted_ages:[18 25 30 45]


**Practice Question:**
You have products = np.array(["Apple", "Banana", "Cherry"]) and sales = np.array([50, 150, 20]). What would np.argsort(sales) return?

In [ ]:
products = np.array(["Apple", "Banana", "Cherry"])
sales= np.array([50, 150, 20])
sorted_indices=np.argsort(sales)
print(sorted_indices) # output: [2 0 1]
# use this indices to reorder product name to see top product
sorted_products=products[sorted_indices]
print(sorted_products) # output: ['Cherry' 'Apple' 'Banana]
# from sorted_product we can see banana is top saled product

[2 0 1]
['Cherry' 'Apple' 'Banana']


# Set Operations in numpy

Set operations are used for comparing arrays. They treat your arrays like "sets" in mathematics—collections of items where **duplicates don't matter** and **order doesn't matter**.

**Finding Unique Elements (np.unique):**

This is the most basic set operation. It finds all the unique items in an array and returns them in sorted order.

In [ ]:
list_A = np.array(["Alice", "Bob", "Charlie", "Bob"])
# list_A. "Bob" is on there twice, but he's only one person.
# let clean it
cleaned_list_A=np.unique(list_A)
print(cleaned_list_A) # output: ['Alice' 'Bob' 'Charlie']
number_list=np.array([1,2,3,2])
unique_numbers=np.unique(number_list)
print(unique_numbers) # output:[1 2 3] unique items in sorted order

['Alice' 'Bob' 'Charlie']
[1 2 3]


**Union and Intersection:**

**np.union1d(a, b):** All unique items that are in either array a or array b.

**np.intersect1d(a, b):** All unique items that are in both array a and array b. (common values)


In [ ]:
# We'll use the unique versions for clarity
a = np.array(["Alice", "Bob", "Charlie"])
b = np.array(["David", "Eve", "Alice"])
# Union
union_ab=np.union1d(a,b)
print(f"union_ab:{union_ab}") # union_ab:['Alice' 'Bob' 'Charlie' 'David' 'Eve']
# intersection
intersection_ab=np.intersect1d(a,b)
print(f"intersection_ab:{intersection_ab}") # intersection_ab:['Alice']

union_ab:['Alice' 'Bob' 'Charlie' 'David' 'Eve']
intersection_ab:['Alice']


**Practice Question**
You have two lists of customers:

last_month = np.array([101, 102, 103, 104])

this_month = np.array([103, 104, 105, 106])

Which customers visited at any point in the last two months?

Which customers visited both last month AND this month?

In [ ]:
last_month = np.array([101, 102, 103, 104])

this_month = np.array([103, 104, 105, 106])

# Which customers visited at any point in the last two months?
union_last_month_this_month=np.union1d(last_month,this_month)
print(f"union_last_month_this_month:{union_last_month_this_month}")

# Which customers visited both last month AND this month?
intersection_last_month_this_month=np.intersect1d(last_month,this_month)
print(f"intersection_last_month_this_month:{intersection_last_month_this_month}")

union_last_month_this_month:[101 102 103 104 105 106]
intersection_last_month_this_month:[103 104]


**np.setdiff1d(a, b) 'a-b':** Items that are in array a but **not** in array b. Order matters here!( np.setdiff1d(a, b) and np.setdiff1d(b, a) are not equall )

**np.setxor1d(a, b):** "Symmetric Difference." Items that are in a or b, but not in both. (inverse of intersection)

In [ ]:
a = np.array(["Alice", "Bob", "Charlie"])
b = np.array(["David", "Eve", "Alice"])
# set difference (a-b)
set_difference_ab=np.setdiff1d(a,b)
print(f"In a ,Not In b:{set_difference_ab}") # In a ,Not In b:['Bob' 'Charlie']
# set difference (b-a)
set_difference_ba=np.setdiff1d(b,a)
print(f"In b ,Not in a:{set_difference_ba}") # In b ,Not in a:['David' 'Eve']
# symmetric difference
symmetric_difference_ab=np.setxor1d(a,b)
print(f"In a or b ,But not in Both:{symmetric_difference_ab}") # In a or b ,Not in both:['Bob' 'Charlie' 'David' 'Eve']

In a ,Not In b:['Bob' 'Charlie']
In b ,Not in a:['David' 'Eve']
In a and b ,But not in Both:['Bob' 'Charlie' 'David' 'Eve']


**Real-World Application:** np.setdiff1d is extremely useful. For an e-commerce site, np.setdiff1d(last_month_customers, this_month_customers) would instantly tell you which customers "churned" (i.e., didn't return this month).

**Final Practice Question (All Concepts)**
You have three arrays: a = np.array([10, 20, 30, 40]) b = np.array([30, 40, 50, 60]) c = np.array([9, 7, 8])

Find the items that are in a or b (or both).

Find the items that are in a but not in b.

Get a "recipe" (indices) that would sort array c.

In [ ]:
a = np.array([10, 20, 30, 40])
b = np.array([30, 40, 50, 60])
c = np.array([9, 7, 8])
# Find the items that are in a or b (or both).
union=np.union1d(a,b)
print(union) # output:[10 20 30 40 50 60]
difference_ab=np.setdiff1d(a,b)
print(difference_ab) # output:[10 20]
# Get indices (of data in c) in sorted order
sorted_indices=np.argsort(c)
print(sorted_indices) # output:[1 2 0]

[10 20 30 40 50 60]
[10 20]
[1 2 0]
